[package]
name = "nullifiable_voting"
type = "contract"
authors = ["Lucid Samuel"]
compiler_version = ">=0.36.0"

[dependencies]
# Remove the aztec dependency for now, as we'll implement the basic contract first