[package]
name = "nullifiable_voting"
type = "contract"
authors = [ "Lucid Samuel" ]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "master" }